### ISSUE TITLE
[INFO] Missing application dependencies

### ISSUE THREAD

**Issue by KashifZA** [katznboyz1/youtube-dl-server#1]
Please add the requirement for the following to get it working: (its mentioned in passing and i didn't see an auto dependency retriever thing so worth mentioning instead of trying to read why its failing)

- gunicorn3
apt install gunicorn3

- flask_session
pip3 install flask_session

Also, user executing needs write access to app and download folders (but this is obvious, for setting up as a service).

**Comment by renamedquery** [comment]
I'll get right on it, there is a requirements.txt file but I realized thats not referenced in the documentation so I see the issue. Thanks!
