### ISSUE TITLE
[BUG] Gunicorn install issue

### ISSUE THREAD

**Issue by lambchop01** [katznboyz1/youtube-dl-server#10]
Hey,  Just an FYI really. I recently got this running in a docker container, however I had to install gunicorn via pip rather than apt-get so that it could find the other modules required (listed in the requirements.txt file.)  Not sure if others had any issue, but thought you may want to update the install instructions.
Cheers

**Comment by renamedquery** [comment]
Oh, weird. I can't be sure if its a docker specific issue but I'll definitely edit the readme and make it pip installed instead of apt-get. Thanks! (will be comitted in a few hours, I'm busy at the moment)

**Comment by Facinorous-420** [comment]
> Hey, Just an FYI really. I recently got this running in a docker container, however I had to install gunicorn via pip rather than apt-get so that it could find the other modules required (listed in the requirements.txt file.) Not sure if others had any issue, but thought you may want to update the install instructions.
> Cheers

Could you share your image/dockerfile? :)

**Comment by lambchop01** [comment]
Sure!  it was a 2 part process, so that you can run the setup script.  I also had to add gunicorn to the requirments.txt file

FROM python:3

RUN apt-get update && apt-get install ffmpeg -y

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

EXPOSE 2456

CMD gunicorn -w 3 -b 0.0.0.0:2456 wsgi:app

Build the image, then run with `docker run -it --entrypoint /bin/bash -p 2456:2456 -v /persistent/file/location:/usr/src/app youtubedl:1` or whatever you tagged the image as. it will send you into the container with a terminal.
Make sure you use a volume, you will need it later
run `python setup.py` follow on screen prompts

Exit out of the container, build the image again from the /persistent/file/location so that the results of setup.py are included.
voila!  it is now exposed on port 2456

**Comment by renamedquery** [comment]
Alrighty, sorry for the 3 week delay, I was busy with school. Gunicorn is now included in the requirements.txt file, thanks for pointing out that issue! Also I may include this dockerfile in a slightly modified version soon, if its okay with you. 

Thanks!

**Comment by lambchop01** [comment]
No problem!  Please feel free to use this dockerfile however you wish.
