### ISSUE TITLE
[Bug] exec: "./startup.sh": permission denied: unknown.

### ISSUE THREAD

**Issue by Plaidstallion** [katznboyz1/youtube-dl-server#17]
After building, I try to run the container and no matter the permissions or if I run docker as sudo I get the following error:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./startup.sh": permission denied: unknown.

I did a git clone to /opt and then cd'd in to youtube-dl-server and ran the build command. I did a `chmod +x startup.sh` and then tried to run the container but no luck. Any suggestions would be appreciated.

My run command is as follows:

```
sudo docker run -dit --name yds --rm -p 8010:8080 \
 -v /opt/youtube-dl-server/downloads:/app/downloads \
 -v /opt/youtube-dl-server/db:/app/db \
 -e APPNAME=YDS \
 -e ADMINUSER=$USER \
 -e PASSWORD=$PW \
 -e TZ=$TZ \
 katznboyz1/youtube-dl-server:latest
```

**Comment by renamedquery** [comment]
Hiya, unfortunately I am not familiar with docker, and I am relying on contributors for docker support, so I can't be sure what is causing this. I'm sure you already googled, and may have even found the same link, but here was a link that seems to describe your problem [https://stackoverflow.com/questions/44687685/getting-permission-denied-in-docker-run](https://stackoverflow.com/questions/44687685/getting-permission-denied-in-docker-run). I will leave this issue open with the hopes of other people chiming in.

**Comment by Plaidstallion** [comment]
Hey thanks! I added the following to the Dockerfile:

`RUN chmod +x startup.sh`
right above
`ENTRYPOINT ["/startup.sh"]`

Fired right up. I have been using images for awhile but as is probably apparent, I have never touched the actual dockerfiles before,

Thanks again.
