### ISSUE TITLE
[Feature] Default download folder & adding new folders manual/back-end only

### ISSUE THREAD

**Issue by KashifZA** [katznboyz1/youtube-dl-server#2]
Not sure how to configure this or is it unchangeable ?

Also is it possible to make adding / removing folders configurable via web (db instead of current text file.. or had it in addition to?)

**Comment by renamedquery** [comment]
Hm I can't believe I didn't think of how impractical this is. I'll add a way to configure it via the web UI either later today or early tomorrow. Also, I will add a way to edit the default download directory. I forgot to change it to a customizable value, currently its hardcoded. I'll get back to this in a few, thanks.

**Comment by renamedquery** [comment]
Just added the feature in the latest commit.
