### ISSUE TITLE
[Feature]Manually edit metadata

### ISSUE THREAD

**Issue by lambchop01** [katznboyz1/youtube-dl-server#9]
Hey, would it be possible to have the ability to edit the metadata such as author/title etc. before downloading?  It could even populate the fields with metadata gathered from the video, then allow the user to edit as necessary.  This would be especially helpful with videos from other sites that do not have metadata to get.

**Comment by renamedquery** [comment]
Yes, that wouldn't be too hard to add. I'm busy for most of today but I'll try to find a time when I can add this feature. Thanks!

**Comment by lambchop01** [comment]
No rush. Just thought it would be handy.

**Comment by renamedquery** [comment]
Alrighty I just finished a feature that allows you to edit the author and title (the only metadata that is supported by this program). If you leave the fields blank, nothing will get overwritten, but if you add stuff to the fields, then the fields will be overwritten.
